version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weather_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  etl:
    build: .
    container_name: weather_etl
    environment:
      DATABASE_URL: postgres://username:password@postgres:5432/weather_db
    volumes:
      - .:/app
    command: ["python", "/app/scripts/etl.py"]  

  app:
    build: .
    depends_on:
      - postgres
    container_name: weather_django
    environment:
      DATABASE_URL: postgres://username:password@postgres:5432/weather_db
      API_KEY: ${API_KEY}
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"] 

volumes:
  pgdata:
