name: ETL Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.11.1
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.1

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: pytest
