# Generated by Django 5.1 on 2024-09-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('temperature_celsius', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('weather', models.CharField(max_length=100)),
                ('wind_speed', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
