name: ETL Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t etl-pipeline .

    - name: Run Docker container and execute tests
      run: |
        docker run -d \
          --name etl-pipeline \
          -e API_KEY=${{ secrets.API_KEY }} \
          -p 8000:8000 \
          etl-pipeline
        docker exec etl-pipeline pytest

    - name: Clean up
      run: |
        docker stop etl-pipeline
        docker rm etl-pipeline
