name: ETL Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
          POSTGRES_DB: weather_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U username"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      run: sudo apt-get install docker-compose

    - name: Build and start services
      run: docker-compose up -d --build

    - name: Run tests
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: docker-compose exec app pytest

    - name: Clean up
      run: |
        docker-compose down
